package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"agent-align/internal/config"
)

// generateCopilotWrapper creates a wrapper script at ~/bin/acp that pre-approves
// the configured allowed tools before invoking the real copilot CLI.
func generateCopilotWrapper(cfg config.Config) error {
	if len(cfg.AllowedTools.AlwaysAllowedTools) == 0 {
		// No allowed tools configured, skip wrapper generation
		return nil
	}

	// Find the real copilot binary
	copilotPath, err := exec.LookPath("copilot")
	if err != nil {
		// Copilot not installed, skip silently
		return nil
	}

	// Create ~/bin directory if it doesn't exist
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}
	binDir := filepath.Join(homeDir, "bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return fmt.Errorf("failed to create ~/bin directory: %w", err)
	}

	// Build the wrapper script content
	script := buildWrapperScript(copilotPath, cfg.AllowedTools.AlwaysAllowedTools)

	// Write the wrapper script
	wrapperPath := filepath.Join(binDir, "acp")
	if err := os.WriteFile(wrapperPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("failed to write wrapper script to %s: %w", wrapperPath, err)
	}

	return nil
}

// buildWrapperScript generates the shell script content for the copilot wrapper.
func buildWrapperScript(copilotPath string, tools []string) string {
	var sb strings.Builder

	// Write the shebang and header
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# Generated by agent-align - do not edit manually\n")
	sb.WriteString(copilotPath)

	// Add each allowed tool as a --allow-tool flag
	for _, tool := range tools {
		sb.WriteString(" --allow-tool '")
		// Escape single quotes in the tool string
		escaped := strings.ReplaceAll(tool, "'", "'\\''")
		sb.WriteString(escaped)
		sb.WriteString("'")
	}

	// Pass through all remaining arguments
	sb.WriteString(` "$@"`)
	sb.WriteString("\n")

	return sb.String()
}
