package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"agent-align/internal/config"
)

// generateCopilotWrapper creates wrapper scripts for each configured agent at
// their specified paths (or ~/.local/bin by default) that pre-approves
// the configured allowed tools before invoking the real copilot CLI.
func generateCopilotWrapper(cfg config.Config) error {
	if len(cfg.AllowedTools.AlwaysAllowedTools) == 0 {
		// No allowed tools configured, skip wrapper generation
		return nil
	}

	// Find the real copilot binary
	copilotPath, err := exec.LookPath("copilot")
	if err != nil {
		// Copilot not installed, skip silently
		return nil
	}

	// Build the wrapper script content once
	script := buildWrapperScript(copilotPath, cfg.AllowedTools.AlwaysAllowedTools)

	// Get home directory for default path
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}
	defaultBinDir := filepath.Join(homeDir, ".local", "bin")

	// Generate wrapper for each configured agent
	for _, agent := range cfg.AllowedTools.Targets.Agents {
		// Use agent-specific path if provided, otherwise use default
		binDir := defaultBinDir
		if agent.Path != "" {
			binDir = agent.Path
		}

		// Create bin directory if it doesn't exist
		if err := os.MkdirAll(binDir, 0o755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", binDir, err)
		}

		// Write the wrapper script with agent name as filename
		wrapperPath := filepath.Join(binDir, "acp")
		if err := os.WriteFile(wrapperPath, []byte(script), 0o755); err != nil {
			return fmt.Errorf("failed to write wrapper script to %s: %w", wrapperPath, err)
		}
	}

	return nil
}

// buildWrapperScript generates the shell script content for the copilot wrapper.
func buildWrapperScript(copilotPath string, tools []string) string {
	var sb strings.Builder

	// Write the shebang and header
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# Generated by agent-align - do not edit manually\n")
	sb.WriteString(copilotPath)

	// Add each allowed tool as a --allow-tool flag
	for _, tool := range tools {
		sb.WriteString(" --allow-tool '")
		// Escape single quotes in the tool string
		escaped := strings.ReplaceAll(tool, "'", "'\\''")
		sb.WriteString(escaped)
		sb.WriteString("'")
	}

	// Pass through all remaining arguments
	sb.WriteString(` "$@"`)
	sb.WriteString("\n")

	return sb.String()
}
